### ISSUE TITLE
Update README file

### ISSUE THREAD

**Issue by hastagAB** [hastagAB/Awesome-Python-Scripts#23]
Update README file with :
(i) the proper description of the Repository
(ii) The List of Python Scripts with their link and Name of Contributors with their Github link anchored.
(iii) Any formatting which looks good and can add something extra related to the repo.

**Comment by Who23** [comment]
@hastagAB May I work on this? Just one question - what do you mean by anchored link?
Thanks!

**Comment by hastagAB** [comment]
@Who23 You are most welcomed to do so.
For Anchored link : [Name to be Displayed](link_address)
Eg : [Ayush Bhardwaj](https://github.com/hastagAB) 
See what it does.

**Comment by zeddmaxx** [comment]
Hey, can I work on this?

**Comment by hastagAB** [comment]
> Hey, can I work on this?

@zeddmaxx Sure you can. :100: 
Each and every contribution is really appreciated. :+1:

**Comment by hastagAB** [comment]
@Who23 & @zeddmaxx .
Any updates on README file?
