### ISSUE TITLE
Arranging of Projects in README.md in alphabetical order.

### ISSUE THREAD

**Issue by hiCXK** [hastagAB/Awesome-Python-Scripts#319]
The projects can be listed in alphabetical order in README.md which will improve readability. Also, some items are repeated which must be deleted.

**Comment by sr2005roy** [comment]
@hiCXK  I would like to work on this. Can you please assign me this issue under the tag of hacktoberfest.

**Comment by hastagAB** [comment]
There is no need for assignments, please go ahead with your contribution.

**Comment by sr2005roy** [comment]
please check this and merge it under hactoberfest label

**Comment by sr2005roy** [comment]
As you have Merged my commit you may close this issue now :)
