### ISSUE TITLE
let's Add some more awesome python scripts

### ISSUE THREAD

**Issue by chaudharyvineet** [hastagAB/Awesome-Python-Scripts#32]
I have a script which uses duckduckgo api to search anything from the terminal itself,i thought it would be cool as coders hate leaving the terminal,plus we don't need an api key for duckduckgo's api as it is public ;).

**Comment by hastagAB** [comment]
@chaudharyvineet Sounds Amazing! :+1:

**Comment by williangl** [comment]
May i work on this too?

**Comment by hastagAB** [comment]
@chaudharyvineet you should mention that in README too.
We should always strive for the minimum number of files and lines in code.
But if you think it is important to include it then go for it.

**Comment by hastagAB** [comment]
> May i work on this too?

@williangl you are most welcome to do so. :+1:
