### ISSUE TITLE
README is still to be Updated. 

### ISSUE THREAD

**Issue by hastagAB** [hastagAB/Awesome-Python-Scripts#43]
#23 
Update README file with :
(i) the proper description of the Repository
(ii) The List of Python Scripts with their link and Name of Contributors with their Github link anchored.
(iii) Any formatting which looks good and can add something extra related to the repo.

**Comment by deadpyxel** [comment]
I can take this issue.

**Comment by hastagAB** [comment]
Sure! @deadpyxel :100:

**Comment by deadpyxel** [comment]
Made the PR, the contributions from chris, prince and Berkay Demir did not lead to any github profile, so I wasn't able to link them. If you find any problems, please let me know.
