### ISSUE TITLE
Add a requirements.txt file to collect all third party dependencies.

### ISSUE THREAD

**Issue by imkaka** [hastagAB/Awesome-Python-Scripts#72]
* Every new script gets added to it will update/append the requirements in the same file if not there.
* If any specific dependency adds a requirements.txt file at each script folder level also.

**Comment by imkaka** [comment]
@hastagAB Let me know if you want me to work on the issue. 👍 

Virtual Environment is a must, we just can't install every package globally.

**Comment by hastagAB** [comment]
Thanks for the suggestion but nobody is going to use each and every script, so having a common requirements.txt is useless for anyone.

Specific requirements for each and every script is already mentioned in their README so that whichever is required can be installed.

**Comment by imkaka** [comment]
A lot of scripts does not mention anything about third party libraries,  It would be better if each script can have consistent README or a local `requirements.txt`. as having common requirements.txt is a bad idea ?

**Comment by hastagAB** [comment]
Yes, I agree but it will be a lot of work as most of the script doesn't have that. One has to check each script manually for that.
If you are willing to take up this work then please go ahead. [In README they have already mentioned the requirements, so it will be a little bit easy to but still, as a solo maintainer I'm unable to do as of now.]

**Comment by imkaka** [comment]
I have already done that in my PR, will go ahead to seperate out for each script.

**Comment by imkaka** [comment]
@hastagAB Please review the PR and merge in the first place as It create `requirements.txt` for already existing scripts in the repo.

* Other scripts PR can cause merge conflict.
* New Script has to follow adding `requirements.txt` to script folder as mentioned at README.

Hope It helps 🍡
